name: "hello world workflow"
# controls when the action will run triggers the workflows on push some to production and master branch
on:
    push:
        branches:
            -master
            -production
jobs:
  hello_world:
     runs-on: windows-latest
     steps:
       - name: "hello worldd"
         run: echo "hello worldd"
